//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renesas.Generator.MCALConfGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renesas.Generator.MCALConfGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOSAR release version information.
        /// </summary>
        internal static string AUTOSAR_RELEASE_VERSION {
            get {
                return ResourceManager.GetString("AUTOSAR_RELEASE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ########################################################################################################################
        ///# AUTOSAR Renesas R{0} {1} Driver Generation Tool for X2x                   
        ///# Run time      = [{2}]
        ///#    Command line arguments = {3}
        ///#
        ///# Copyright(c) 2023, 2024 Renesas Electronics Corporation. All rights reserved.
        ///########################################################################################################################
        ///
        ///.
        /// </summary>
        internal static string CopyRightLog {
            get {
                return ResourceManager.GetString("CopyRightLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*====================================================================================================================*/
        ////* Project      = AUTOSAR Renesas $$MicroFamilyName:100:: MCAL Components$$*/
        ////* Module       = $$FileName:100:L$$*/
        ////*====================================================================================================================*/
        ////*                                  COPYRIGHT                                                                         */
        ////*========================= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CopyrightTemplate {
            get {
                return ResourceManager.GetString("CopyrightTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dlls.
        /// </summary>
        internal static string DLLS_PATH {
            get {
                return ResourceManager.GetString("DLLS_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #endif /* {0} */.
        /// </summary>
        internal static string END_MACRO_TEMPLATE {
            get {
                return ResourceManager.GetString("END_MACRO_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END Msg{0}.
        /// </summary>
        internal static string EndQac {
            get {
                return ResourceManager.GetString("EndQac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of fields is not same for the entity &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_SPECIFIC_01 {
            get {
                return ResourceManager.GetString("ERR_SPECIFIC_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is empty in the entity &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_SPECIFIC_02 {
            get {
                return ResourceManager.GetString("ERR_SPECIFIC_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &lt;{0}&gt; does not exist..
        /// </summary>
        internal static string ERR000001 {
            get {
                return ResourceManager.GetString("ERR000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Generation Tool configuration XML file is not given along with the &lt;{0}&gt; option..
        /// </summary>
        internal static string ERR000002 {
            get {
                return ResourceManager.GetString("ERR000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the &lt;{0}&gt; file..
        /// </summary>
        internal static string ERR000004 {
            get {
                return ResourceManager.GetString("ERR000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of output directory is not given along with &lt;{0}&gt; option..
        /// </summary>
        internal static string ERR000005 {
            get {
                return ResourceManager.GetString("ERR000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of output directory is not given in OUTPUT-PATH tag in &lt;{0}&gt; file..
        /// </summary>
        internal static string ERR000006 {
            get {
                return ResourceManager.GetString("ERR000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Generation Tool expects inputs..
        /// </summary>
        internal static string ERR000007 {
            get {
                return ResourceManager.GetString("ERR000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option &lt;{0}&gt; is not supported by the Generation Tool. The Generation Tool supports  &lt;-m/-module , -O/-OUTPUT, -Osrc, -Oinc, -H/-HELP, -L/-LOG, -C/-CONFIGFILE, -FR/-FILTER and -D/-DRYRUN&gt; options..
        /// </summary>
        internal static string ERR000008 {
            get {
                return ResourceManager.GetString("ERR000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output directory name &lt;{0}&gt; as the file with same name exists..
        /// </summary>
        internal static string ERR000009 {
            get {
                return ResourceManager.GetString("ERR000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output directory name &lt;{0}&gt; Directory name should not contain any of \*\?\&quot;\|\: characters..
        /// </summary>
        internal static string ERR000010 {
            get {
                return ResourceManager.GetString("ERR000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU Configuration Description File is not provided as input to the Generation Tool..
        /// </summary>
        internal static string ERR000011 {
            get {
                return ResourceManager.GetString("ERR000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input &lt;{0}&gt; is not as per XML standard. Provide the ECU Configuration Description File as input on the command line..
        /// </summary>
        internal static string ERR000012 {
            get {
                return ResourceManager.GetString("ERR000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; should contain the &apos;TRANSLATION-FILE-PATH&apos; and &apos;DEVICE-FILE-PATH&apos; tags..
        /// </summary>
        internal static string ERR000013 {
            get {
                return ResourceManager.GetString("ERR000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;TRANSLATION-FILE-PATH&apos; tag in &lt;{0}&gt; is empty..
        /// </summary>
        internal static string ERR000014 {
            get {
                return ResourceManager.GetString("ERR000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; tag should be present as child of &apos;TRANSLATION-FILE-PATH&apos; tag in &lt;{1}&gt;..
        /// </summary>
        internal static string ERR000015 {
            get {
                return ResourceManager.GetString("ERR000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;DEVICE-FILE-PATH&apos; tag in &lt;{0}&gt; is empty..
        /// </summary>
        internal static string ERR000016 {
            get {
                return ResourceManager.GetString("ERR000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; tag should be present as child of &apos;DEVICE-FILE-PATH&apos; tag in &lt;{1}&gt;..
        /// </summary>
        internal static string ERR000017 {
            get {
                return ResourceManager.GetString("ERR000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create directory &lt;{0}&gt;. {1}.
        /// </summary>
        internal static string ERR000018 {
            get {
                return ResourceManager.GetString("ERR000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open &lt;{0}&gt; file..
        /// </summary>
        internal static string ERR000019 {
            get {
                return ResourceManager.GetString("ERR000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The macro label &lt;{0}&gt; should be unique in &lt;{1}&gt; translation C Header File..
        /// </summary>
        internal static string ERR000020 {
            get {
                return ResourceManager.GetString("ERR000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The macro definition for &lt;{0}&gt; macro is not found in &lt;{1}&gt; translation C Header File..
        /// </summary>
        internal static string ERR000021 {
            get {
                return ResourceManager.GetString("ERR000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The macro value for &lt;{0}&gt; macro is empty in &lt;{1}&gt; translation C Header File..
        /// </summary>
        internal static string ERR000022 {
            get {
                return ResourceManager.GetString("ERR000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The macro definition for &lt;{0}&gt; macro is not found in &lt;{1}&gt; device specific C Header File(s)..
        /// </summary>
        internal static string ERR000023 {
            get {
                return ResourceManager.GetString("ERR000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The macro value for &lt;{0}&gt; macro is empty in &lt;{1}&gt; device specific C Header File(s)..
        /// </summary>
        internal static string ERR000024 {
            get {
                return ResourceManager.GetString("ERR000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &lt;{0}&gt; provided for Bsw Module is dupplicated..
        /// </summary>
        internal static string ERR000025_DUPPLICATED {
            get {
                return ResourceManager.GetString("ERR000025_DUPPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &lt;{0}&gt; provided for Bsw Module is incorrect..
        /// </summary>
        internal static string ERR000025_INCORRECT {
            get {
                return ResourceManager.GetString("ERR000025_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSWMDT content is not present in the input file(s) for &apos;{0}&apos; module..
        /// </summary>
        internal static string ERR000026 {
            get {
                return ResourceManager.GetString("ERR000026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;MODULE-DESCRIPTION-REF&apos; element should be present in the description file of &apos;{0}&apos; module..
        /// </summary>
        internal static string ERR000028 {
            get {
                return ResourceManager.GetString("ERR000028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOSAR version &apos;{0}&apos; of BSWMDT File is inconsistence with ECU Configuration Description File of &apos;{1}&apos; device..
        /// </summary>
        internal static string ERR000029 {
            get {
                return ResourceManager.GetString("ERR000029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; tag should be configured in BSWMDT File..
        /// </summary>
        internal static string ERR000030 {
            get {
                return ResourceManager.GetString("ERR000030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name is not specified by option &lt;-m&gt; or NOT in supported modules &lt;{0}&gt;.
        /// </summary>
        internal static string ERR000031 {
            get {
                return ResourceManager.GetString("ERR000031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter value is not given along with &lt;-FR/-FILTER&gt; option..
        /// </summary>
        internal static string ERR000032 {
            get {
                return ResourceManager.GetString("ERR000032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options &lt;{0}&gt; should be set explicitly by command line options and configuration file..
        /// </summary>
        internal static string ERR000034 {
            get {
                return ResourceManager.GetString("ERR000034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSWMDT file is not provided as input to the Generation Tool..
        /// </summary>
        internal static string ERR000036 {
            get {
                return ResourceManager.GetString("ERR000036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The register label &lt;{0}&gt; should be unique in &lt;{1}&gt; device C Header File..
        /// </summary>
        internal static string ERR000037 {
            get {
                return ResourceManager.GetString("ERR000037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The register address &lt;{0}&gt; has invalid Hex value in &lt;{1}&gt; device C Header File..
        /// </summary>
        internal static string ERR000038 {
            get {
                return ResourceManager.GetString("ERR000038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name is NOT specified in CDF files..
        /// </summary>
        internal static string ERR000039 {
            get {
                return ResourceManager.GetString("ERR000039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one BSWMDT files are provided as input to the Generation Tool..
        /// </summary>
        internal static string ERR000040 {
            get {
                return ResourceManager.GetString("ERR000040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_E_INT_INCONSISTENT should be configured when the parameter {1}InterruptConsistencyCheck is true..
        /// </summary>
        internal static string ERR000041 {
            get {
                return ResourceManager.GetString("ERR000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file is not compatible.
        /// </summary>
        internal static string ERR000043 {
            get {
                return ResourceManager.GetString("ERR000043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  file is not found or wrong {0} for module {1}.
        /// </summary>
        internal static string ERR000045 {
            get {
                return ResourceManager.GetString("ERR000045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect device name &apos;{0}&apos;. Generation tool supports device name(s): {1}..
        /// </summary>
        internal static string ERR000046 {
            get {
                return ResourceManager.GetString("ERR000046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vendor data found from CDF files.
        /// </summary>
        internal static string ERR000047 {
            get {
                return ResourceManager.GetString("ERR000047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} in BSWMDT is not match to path {1} in CDF files.
        /// </summary>
        internal static string ERR000048 {
            get {
                return ResourceManager.GetString("ERR000048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENDOR-SPECIFIC-MODULE-DEF-REF is not exists in BSWMDT.
        /// </summary>
        internal static string ERR000049 {
            get {
                return ResourceManager.GetString("ERR000049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission to perform action: {0} {1}. {2}.
        /// </summary>
        internal static string ERR000050 {
            get {
                return ResourceManager.GetString("ERR000050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path too long, cannot perform action: {0} {1}. {2}.
        /// </summary>
        internal static string ERR000051 {
            get {
                return ResourceManager.GetString("ERR000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while perform action {0} the file {1}. {2}.
        /// </summary>
        internal static string ERR000053 {
            get {
                return ResourceManager.GetString("ERR000053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load file {0}. {1}.
        /// </summary>
        internal static string ERR000055 {
            get {
                return ResourceManager.GetString("ERR000055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad DLL format, unable to load file {0}. {1}.
        /// </summary>
        internal static string ERR000056 {
            get {
                return ResourceManager.GetString("ERR000056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variant criterion between &quot;{0} CDF&quot;  and &quot;EvaluatedVariantSet&quot; must be the same..
        /// </summary>
        internal static string ERR000057 {
            get {
                return ResourceManager.GetString("ERR000057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variant ID between &quot;{0}&quot; container and &quot;{1}&quot; parameters/references must be the same..
        /// </summary>
        internal static string ERR000058 {
            get {
                return ResourceManager.GetString("ERR000058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variant ID in the CDF config of the &quot;{0}&quot;  is not existed in &quot;EvaluatedVariantSet&quot;..
        /// </summary>
        internal static string ERR000059 {
            get {
                return ResourceManager.GetString("ERR000059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one EvaluatedVariantSet file can be included..
        /// </summary>
        internal static string ERR000060 {
            get {
                return ResourceManager.GetString("ERR000060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \GenerationTool.log.
        /// </summary>
        internal static string GENTOOL_LOG_FILE {
            get {
                return ResourceManager.GetString("GENTOOL_LOG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*                                                                                                                    */
        ////* TOOL VERSION:  $$Version:99:L$$ */
        ////*                                                                                                                    */.
        /// </summary>
        internal static string GentoolVersionTemplate {
            get {
                return ResourceManager.GetString("GentoolVersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOSAR Renesas Driver Generation Tool for X2x
        ///OVERVIEW :
        ///&lt;MSN&gt; Driver Generation Tool is a Command &lt;MSN&gt; Tool, which accepts
        ///the ECU Configuration Description File, BSWMDT File, Translation
        ///XML File (which contain the translation and device specific header
        ///file path) and Configuration XML File (which contains the seeting of
        ///command line options) as input and generates the
        ///&lt;MSN&gt; Driver C source and C Header files as output.
        ///
        ///USAGE:
        ///McalConfGen.exe [&lt;Options&gt; {&lt;Input Filename&gt;}]
        ///Input Filename: EC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpToolTemplate {
            get {
                return ResourceManager.GetString("HelpToolTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Version: {0} version: {1}, {2} version: {3}.
        /// </summary>
        internal static string INF000001 {
            get {
                return ResourceManager.GetString("INF000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments: {0} {1}.
        /// </summary>
        internal static string INF000002 {
            get {
                return ResourceManager.GetString("INF000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid inputs are provided below..
        /// </summary>
        internal static string INF000003 {
            get {
                return ResourceManager.GetString("INF000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened file &lt;{0}&gt; at [{1}]..
        /// </summary>
        internal static string INF000004 {
            get {
                return ResourceManager.GetString("INF000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Error(s) and &lt;{1}&gt; Warning(s) detected..
        /// </summary>
        internal static string INF000005 {
            get {
                return ResourceManager.GetString("INF000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution completed successfully..
        /// </summary>
        internal static string INF000006 {
            get {
                return ResourceManager.GetString("INF000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution completed successfully with warnings..
        /// </summary>
        internal static string INF000007 {
            get {
                return ResourceManager.GetString("INF000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution terminated due to command line errors..
        /// </summary>
        internal static string INF000008 {
            get {
                return ResourceManager.GetString("INF000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution terminated due to error in the input file..
        /// </summary>
        internal static string INF000009 {
            get {
                return ResourceManager.GetString("INF000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution terminated due to error, during the structure generation in the output file..
        /// </summary>
        internal static string INF000010 {
            get {
                return ResourceManager.GetString("INF000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution terminated because file cannot be overwritten since it is read only..
        /// </summary>
        internal static string INF000011 {
            get {
                return ResourceManager.GetString("INF000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution terminated because loaded dll file is not compatible.
        /// </summary>
        internal static string INF000012 {
            get {
                return ResourceManager.GetString("INF000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution terminated because specific dll file is not found.
        /// </summary>
        internal static string INF000014 {
            get {
                return ResourceManager.GetString("INF000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * INPUT FILE:    $$Files$$
        /// * GENERATED ON:  $$Time$$
        /// */.
        /// </summary>
        internal static string InputFilesTemplate {
            get {
                return ResourceManager.GetString("InputFilesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADC,CAN,DIO,ETH,FLS,FR,GPT,ICU,LIN,MCU,PORT,PWM,SPI,WDG,RAMTST,OCU,CORTST,FLSTST.
        /// </summary>
        internal static string MCAL_MODULES {
            get {
                return ResourceManager.GetString("MCAL_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* 1. MISRA C RULE VIOLATION:                                                 */
        ////* Message       : (4:0303) Cast between a pointer to volatile object and     */
        ////*                 an integral type.                                          */
        ////* Rule          : MISRA-C:2004 Rule 11.3                                     */
        ////*                 REFERENCE - ISO-6.3.4 Semantics                            */
        ////* Justification : Typecasting is done as per the register size, to access    */
        ////*                 h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MisraCTemplate {
            get {
                return ResourceManager.GetString("MisraCTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISRA Violation.
        /// </summary>
        internal static string MisraPrefix {
            get {
                return ResourceManager.GetString("MisraPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAC Warning.
        /// </summary>
        internal static string QacPrefix {
            get {
                return ResourceManager.GetString("QacPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleId,SwVersion,VendorId,ArReleaseVersion.
        /// </summary>
        internal static string RequiredBswFields {
            get {
                return ResourceManager.GetString("RequiredBswFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifndef {0}
        ///#define {0}.
        /// </summary>
        internal static string START_MACRO_TEMPLATE {
            get {
                return ResourceManager.GetString("START_MACRO_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: START Msg{1}.
        /// </summary>
        internal static string StartQac {
            get {
                return ResourceManager.GetString("StartQac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As per AUTOSAR ECU Configuration Description File naming convention, the file extension should be &apos;.arxml&apos; for &apos;{0}&apos; file..
        /// </summary>
        internal static string WRN000001 {
            get {
                return ResourceManager.GetString("WRN000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are duplications in command lines: &apos;{0}&apos;..
        /// </summary>
        internal static string WRN000002 {
            get {
                return ResourceManager.GetString("WRN000002", resourceCulture);
            }
        }
    }
}
